version: "3.4"

services:
  php:
    container_name: symfony_php
    build:
      context: php/
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-4.4.*}
        STABILITY: ${STABILITY:-stable}
    image: symfony_php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      # Comment out the next line in production
      - ./app:/srv/app:rw,cached
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /srv/app/var/
      - /srv/app/var/cache/
      - /srv/app/var/logs/
      - /srv/app/var/sessions/
    environment:
      - SYMFONY_VERSION

  nginx:
    container_name: symfony_nginx
    build:
      context: nginx/
      target: symfony_nginx
    depends_on:
      - php
    volumes:
      # Comment out the next line in production
      - ./nginx/nginx-conf/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    ports:
      - "80:80"
  
  # This HTTP/2 proxy is not secure: it should only be used in dev
  h2-proxy:
    container_name: symfony_proxy
    build:
      context: ./nginx
      target: symfony_h2-proxy
    depends_on:
      - nginx
    volumes:
      - ./nginx/h2-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "443:443"